Repository izothep-projects/projects-test, pull requests merged in 2020-02, with the labels that each got.

#20 Create test2
  test2.js
Labels: Status: For Review

#7 Create test
  test
Labels: Status: For Review

#43 Create test6
  test6
Labels: Status: For Review, documentation, duplicate

#47 2.1.
  1
Labels: Status: For Review, documentation, duplicate

#57 Create test9
  test9
Labels: Status: For Review, documentation
